#!/usr/bin/env python3
"""Generate the DLL-side entity-lump identity manifest from the BSP audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
from typing import Any, Sequence


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_AUDIT = ROOT / "docs" / "audits" / "bsp-entities.json"
DEFAULT_OUTPUT = ROOT / "src" / "zaero" / "g_zaero_shipped_map_identity.h"
SHA256_RE = re.compile(r"[0-9a-f]{64}\Z")
MAPNAME_RE = re.compile(r"z(?:base|def|waste|tomb|boss|dm)[0-9]*\Z")
EXPECTED_NAMES = frozenset(
    (
        "zbase1", "zbase2", "zdef1", "zdef2", "zdef3", "zdef4",
        "zwaste1", "zwaste2", "zwaste3", "ztomb1", "ztomb2", "ztomb3",
        "ztomb4", "zboss", "zdm1", "zdm2", "zdm3", "zdm4", "zdm5", "zdm6",
    )
)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", type=Path, default=DEFAULT_AUDIT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail unless --output is current")
    return parser.parse_args(argv)


def _digest_bytes(value: str) -> str:
    return ", ".join(f"0x{value[index:index + 2]}" for index in range(0, 64, 2))


def load_records(path: Path) -> list[dict[str, str]]:
    try:
        audit: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read BSP audit {path}: {error}") from error
    if audit.get("format") != "ZaeREo BSP entity audit":
        raise ValueError("unexpected BSP audit format")
    maps = audit.get("maps")
    if not isinstance(maps, list):
        raise ValueError("BSP audit maps must be an array")
    records: list[dict[str, str]] = []
    for item in maps:
        if not isinstance(item, dict):
            raise ValueError("BSP audit map record must be an object")
        mapname = item.get("map_name")
        bsp_hash = item.get("sha256")
        entity_hash = item.get("entity_lump_sha256")
        if not isinstance(mapname, str) or not MAPNAME_RE.fullmatch(mapname):
            raise ValueError(f"invalid canonical map name: {mapname!r}")
        if not isinstance(bsp_hash, str) or not SHA256_RE.fullmatch(bsp_hash):
            raise ValueError(f"invalid full BSP SHA-256 for {mapname}")
        if not isinstance(entity_hash, str) or not SHA256_RE.fullmatch(entity_hash):
            raise ValueError(f"invalid entity-lump SHA-256 for {mapname}")
        records.append(
            {"map_name": mapname, "sha256": bsp_hash, "entity_lump_sha256": entity_hash}
        )
    names = {record["map_name"] for record in records}
    if names != EXPECTED_NAMES or len(records) != len(EXPECTED_NAMES):
        raise ValueError("BSP audit must contain exactly the 20 audited Zaero retail maps")
    return sorted(records, key=lambda record: record["map_name"].encode("ascii"))


def render(records: list[dict[str, str]]) -> str:
    lines = [
        "// Generated by tools/generate_shipped_map_identity.py from docs/audits/bsp-entities.json.",
        "// Do not edit by hand. Full BSP SHA-256 values remain in the audit; the",
        "// game DLL can verify only the entity text supplied by the engine API.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "struct zaero_shipped_map_identity_t",
        "{",
        "\tconst char *mapname;",
        "\tstd::array<uint8_t, 32> entity_lump_sha256;",
        "};",
        "",
        "static constexpr std::array<zaero_shipped_map_identity_t, 20> zaero_shipped_map_identities = {{",
    ]
    for record in records:
        lines.extend(
            (
                "\t{",
                f'\t\t"{record["map_name"]}",',
                f"\t\t{{ { _digest_bytes(record['entity_lump_sha256']) } }},",
                "\t},",
            )
        )
    lines.extend(("}};", ""))
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        rendered = render(load_records(args.audit))
        if args.check:
            actual = args.output.read_text(encoding="utf-8") if args.output.exists() else None
            if actual != rendered:
                print(f"{args.output}: generated shipped-map identity is stale", file=sys.stderr)
                return 1
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(rendered, encoding="utf-8", newline="\n")
    except ValueError as error:
        print(f"generate_shipped_map_identity.py: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
